### ISSUE TITLE
not compiling 

### ISSUE THREAD

**Issue by smagtech** [playduck/pico-dsp#1]
I'm getting this error. need help please. and also need wiring diagram. 
![Screenshot (43)](https://github.com/playduck/pico-dsp/assets/27198281/a57e0cc6-8d44-42d4-a98b-72e2c974f6ee)

**Comment by playduck** [comment]
Hi,

could you provide a little more information on the error you're getting and on your environment?
A log of the compile output would be helpful.
What version of the SDK/compiler etc are you using?

The exact wiring will depend on your hardware ADC/DAC/CODEC.
For now only I2S is supported.

Generally the project implements two I2S master interfaces.
One interface for sending data and one for receiving.
The MCLK (sometimes also called SCK) is common to both interfaces.
Both interfaces have a BCLK and an LRCLK (sometimes called WS) and a data pin for either receiving or transmitting.
The pins are defined in [main.cpp:26](https://github.com/playduck/pico-dsp/blob/master/main.cpp#L26-L30).
Note: As the I2S interface is implemented via the PIOs, the LRCLK is defined implicitly.
The LRCLK pin number is always the BCLK pin plus one (so for example the `input_BCLK_Base` is 3, then the `input_LRCLK` will be on pin 4).

**Comment by smagtech** [comment]
Hi,
thank you for reply.

Hardware is....
I2S coming from raspberry pi volumio player. Bclk, LRclk, & Data. and my DSP ADAU1701 need Mclk, Bclk, LRclk, & Data. All 4 signal of DSP ADAU1701 need to be in synchronize or it wont work. I tried to feed external Mclk 12.288,Mhz between PI and DSP it wont work because it not synchronize. attaching image of  Bclk Mclk in synchronized.
![IMG_20231116_101228](https://github.com/playduck/pico-dsp/assets/27198281/07ce1193-7127-4d51-b6fc-1515df8dfc35)

I was thinking of
From PI   >>>>>>>>>>>>>>>>>>>>>>>>      To DSP ADAU1701  
LRclk ------------------------------------------------------- LRclk
Data ------------------------------------------------------- Data
Bclk   ------------------------------------------------------- Bclk 
!                                                                       
!-GPIO in  ----synchronize Mclk GPIO out--------------- Mclk 
Roll of RP2040 PICO is synchronize Mclk with Bclk. 
is this possible ^.
                                                                                               
Software is....
Pico - Visual studio  code.
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045


error is.......
[main] Building folder: pico-dsp-master 
[build] Starting build
[proc] Executing command: "C:\Program Files\Raspberry Pi\Pico SDK v1.5.1\cmake\bin\cmake.EXE" --build c:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/build --config Debug --target all --
[build] [6/64   1% :: 0.489] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
[build] [7/64   3% :: 0.506] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/common/pico_util/datetime.c.obj
[build] [8/64   4% :: 0.574] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/common/pico_util/pheap.c.obj
[build] [9/64   6% :: 0.711] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
[build] [10/64   7% :: 0.807] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
[build] [11/64   9% :: 0.908] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
[build] [12/64  10% :: 0.960] Building ASM object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
[build] [13/64  12% :: 1.028] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
[build] [14/64  14% :: 1.160] Building ASM object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
[build] [15/64  15% :: 1.325] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
[build] [16/64  17% :: 1.360] Building CXX object CMakeFiles/pico-dsp.dir/main.cpp.obj
[build] FAILED: CMakeFiles/pico-dsp.dir/main.cpp.obj 
[build] C:\PROGRA~1\RASPBE~1\PICOSD~1.1\GCC-AR~1\bin\AR10B2~1.EXE -DCFG_TUSB_MCU=OPT_MCU_RP2040 -DCFG_TUSB_OS=OPT_OS_PICO -DLIB_PICO_BIT_OPS=1 -DLIB_PICO_BIT_OPS_PICO=1 -DLIB_PICO_DIVIDER=1 -DLIB_PICO_DIVIDER_HARDWARE=1 -DLIB_PICO_DOUBLE=1 -DLIB_PICO_DOUBLE_PICO=1 -DLIB_PICO_FIX_RP2040_USB_DEVICE_ENUMERATION=1 -DLIB_PICO_FLOAT=1 -DLIB_PICO_FLOAT_PICO=1 -DLIB_PICO_INT64_OPS=1 -DLIB_PICO_INT64_OPS_PICO=1 -DLIB_PICO_MALLOC=1 -DLIB_PICO_MEM_OPS=1 -DLIB_PICO_MEM_OPS_PICO=1 -DLIB_PICO_MULTICORE=1 -DLIB_PICO_PLATFORM=1 -DLIB_PICO_PRINTF=1 -DLIB_PICO_PRINTF_PICO=1 -DLIB_PICO_RUNTIME=1 -DLIB_PICO_STANDARD_LINK=1 -DLIB_PICO_STDIO=1 -DLIB_PICO_STDIO_USB=1 -DLIB_PICO_STDLIB=1 -DLIB_PICO_SYNC=1 -DLIB_PICO_SYNC_CRITICAL_SECTION=1 -DLIB_PICO_SYNC_MUTEX=1 -DLIB_PICO_SYNC_SEM=1 -DLIB_PICO_TIME=1 -DLIB_PICO_UNIQUE_ID=1 -DLIB_PICO_UTIL=1 -DPICO_BOARD=\"pico\" -DPICO_BUILD=1 -DPICO_CMAKE_BUILD_TYPE=\"Debug\" -DPICO_COPY_TO_RAM=0 -DPICO_CXX_ENABLE_EXCEPTIONS=0 -DPICO_EXTRAS=1 -DPICO_NO_FLASH=0 -DPICO_NO_HARDWARE=0 -DPICO_ON_DEVICE=1 -DPICO_PROGRAM_NAME=\"dsp\" -DPICO_PROGRAM_VERSION_STRING=\"0.1\" -DPICO_RP2040_USB_DEVICE_UFRAME_FIX=1 -DPICO_TARGET_NAME=\"pico-dsp\" -DPICO_USE_BLOCKED_RAM=0 -IC:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/src -IC:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/build -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/common/pico_stdlib/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_gpio/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/common/pico_base/include" -IC:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/build/generated/pico_base -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/boards/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_platform/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2040/hardware_regs/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_base/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2040/hardware_structs/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_claim/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_sync/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_irq/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/common/pico_sync/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/common/pico_time/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_timer/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/common/pico_util/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_uart/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_resets/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_clocks/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_pll/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_vreg/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_watchdog/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_xosc/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_divider/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_runtime/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_printf/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/common/pico_bit_ops/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/common/pico_divider/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_double/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_float/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_malloc/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_bootrom/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/common/pico_binary_info/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_stdio/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_stdio_usb/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_unique_id/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_flash/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/common/pico_usb_reset_interface/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_int64_ops/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_mem_ops/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/boot_stage2/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/lib/tinyusb/src" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/lib/tinyusb/src/common" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/lib/tinyusb/hw" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_fix/rp2040_usb_device_enumeration/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_pio/include" -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/hardware_dma/include" -IC:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/build/pico_extras/src/rp2_common/pico_audio_i2s -IC:/Users/G_Sudhir/Documents/Pico-v1.5.1/pico-extras/src/rp2_common/pico_audio_i2s/include -IC:/Users/G_Sudhir/Documents/Pico-v1.5.1/pico-extras/src/common/pico_audio/include -IC:/Users/G_Sudhir/Documents/Pico-v1.5.1/pico-extras/src/common/pico_util_buffer/include -I"C:/Program Files/Raspberry Pi/Pico SDK v1.5.1/pico-sdk/src/rp2_common/pico_multicore/include" -O3 -march=armv6-m -mcpu=cortex-m0plus -mthumb -ffunction-sections -fdata-sections -fno-exceptions -Wall -Wextra -Og -g -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-rtti -fno-use-cxa-atexit -std=gnu++17 -MD -MT CMakeFiles/pico-dsp.dir/main.cpp.obj -MF CMakeFiles\pico-dsp.dir\main.cpp.obj.d -o CMakeFiles/pico-dsp.dir/main.cpp.obj -c C:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/main.cpp
[build] C:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/main.cpp: In function 'int main()':
[build] C:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/main.cpp:114:29: error: conversion from 'int' to non-scalar type 'absolute_time_t' requested
[build]   114 |     absolute_time_t start = 0, end = 0;
[build]       |                             ^
[build] C:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/main.cpp:114:38: error: conversion from 'int' to non-scalar type 'absolute_time_t' requested
[build]   114 |     absolute_time_t start = 0, end = 0;
[build]       |                                      ^
[build] [16/64  18% :: 1.452] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
[build] [16/64  20% :: 1.487] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
[build] [16/64  21% :: 1.503] Building ASM object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
[build] [16/64  23% :: 1.704] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/common/pico_util/queue.c.obj
[build] [16/64  25% :: 1.713] Building C object CMakeFiles/pico-dsp.dir/C_/Program_Files/Raspberry_Pi/Pico_SDK_v1.5.1/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
[build] ninja: build stopped: subcommand failed.
[proc] The command: "C:\Program Files\Raspberry Pi\Pico SDK v1.5.1\cmake\bin\cmake.EXE" --build c:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/build --config Debug --target all -- exited with code: 1
[driver] Build completed: 00:00:01.806
[build] Build finished with exit code 1

**Comment by playduck** [comment]
Unfortunately I can't reproduce your compilation issue. The repo build fine on my machine.
However, I'm probably not using the latest builds. Perhaps check if your tool version differ from mine:
- cmake version 3.27.7
- pico-sdk: f396d05f8252d4670d4ea05c8b7ac938ef0cd381

Nonetheless, it sounds like you're asking an ["xy"-problem](https://xyproblem.info), as you don't want to use the project for its intended purpose (although this repo could work if both RPI and ADAU are configured in I2S slave mode).
I'm pretty sure a raspberry pi and an ADAU dsp can exchange I2S data without any additional hardware in-between.
The PI might not be able to output an MCLK but the ADAU surely has some ASRC's on board.
With a quick google search I found this repo: https://github.com/MKSounds/ADAU1701-I2S-Audio-Driver-for-Raspberry-Pi
It looks like it provides some device-tree overlays to interface an RPI with a ADAU1701 natively.
It even provides an installation guide for Volumio images.

**Comment by smagtech** [comment]
[{
	"resource": "/C:/Users/G_Sudhir/Desktop/RP2040_I2S/pico-dsp-master/pico-dsp-master/main.cpp",
	"owner": "cmake-build-diags",
	"severity": 8,
	"message": "conversion from 'int' to non-scalar type 'absolute_time_t' requested",
	"source": "GCC",
	"startLineNumber": 114,
	"startColumn": 38,
	"endLineNumber": 114,
	"endColumn": 1000
}]

main,cpp

line 114

    absolute_time_t start = 0, end = 0;

not able to solve this.

**Comment by playduck** [comment]
I can't reproduce this issue. The project works fine on my machine.
This must be a problem with your setup. I can't help with that.

**Comment by smagtech** [comment]
ok thank you.
